Entrega_Final_Arcenilla_Miotto/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('post/', include('post.urls')),
    path('comment/', include('comment.urls')),
    path('user/', include('user.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path
from comment import views

app_name='comment'
urlpatterns =[
    path('comentarios',views.comentarios, name='Comentarios'),
    path('comentario_formulario/<int:pk>', views.comentario_formulario , name='ComentarioFormulario'),
]

home/urls.py
from django.urls import path

from home import views

app_name='home'
urlpatterns = [
    path('', views.main, name='main'),
    path('pagina_error', views.pagina_error, name='pagina-error'),
    path('about_us', views.about_us, name='about-us'),
]

post/urls.py
from django.urls import path
from post import views

app_name='post'
urlpatterns =[
    path('post', views.PostListView.as_view(), name='post-list'),
    path('post/add/', views.PostCreateView.as_view(), name='post-add'),
    path('post/<int:pk>/detail', views.PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', views.PostDeleteView.as_view(), name='post-delete'),
    path('post_search', views.post_search, name='post-search'),
    path('imagen/<int:pk>/load', views.imagen_load, name='imagen-load'),
    
]

user/urls.py
from django.urls import path

from user import views


app_name='user'
urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path('user/<int:pk>/detail', views.AutorDetailView.as_view(), name='autor-detail'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.db.models import Q

from user.models import Avatar
from post.models import Post


def main(request):
    avatar_ctx = get_avatar_url_ctx(request)
    posts= Post.objects.all()
    context_dict = {**avatar_ctx, 'posts': posts}
    return render(
        request=request,
        context=context_dict,
        template_name="home/main.html"
    )

def get_avatar_url_ctx(request):
    avatars = Avatar.objects.filter(user=request.user.id)
    if avatars.exists():
        return {"url": avatars[0].image.url}
    return {}

def pagina_error(request):
    return render(
        request=request,
        template_name="home/pagina_error.html"
    )

def about_us(request):
    return render(
        request=request,
        template_name="home/about_us.html"
    )

home/templates/home/about_us.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}
<div class="col-md-4 float-right ">
    <div class="card my-4">
            <h5 class="card-header">About Us</h5>
        <div class="card-body">
            <p class="card-text"> Amadeo Miotto is my name , borned and raised in Argentina with dual citizienship italian/argentinian .I enrolled at Coder House which is a school of digital skills to learn a Programming languaje named Python, During the 3 months of course I Learnt the basics of Python and how to portray my code with the help of Visual Studio Code (Code editor) , Sql (Date base management) and Django (Web Framework). This blog was created as the final presentation of Python's Coder house digital skills school!</p>
            <a href="https://ar.linkedin.com/in/amadeo-miotto-a3a135223"class="btn btn-blue">Know more about Amadeo Miotto!! My linkedin Profile clicking here! </a>  
            
        </div>
    </div>
</div>

{% endblock %}

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {%load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>CoderBlog</title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico'%}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href= "{% static 'home/css/styles.css' %}" rel="stylesheet" />
        <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
        <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:main'%}">CODER'S HOUSE BLOG</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:main' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'post:post-list'%}">Publications</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'post:post-search' %}"><i class="fa fa-search" style="color: hsl(240, 71%, 99%);"></a></i></li>
                        </a>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'comment:Comentarios'%}">Comments</a></li>
                        <a class="btn btn-secondary" href="{% url 'user:user-update' %}">Update user</a>
                        <a class="btn btn-primary" href="{% url 'user:user-logout' %}">Log out!</a>
                        {% else %}
                        <a class="btn btn-primary" href="{% url 'user:user-login' %}">Log in!</a>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header--> 
        <header class="masthead" style=background-image:url({% static 'home/assets/img/home-bg.jpg' %})>
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Coder Blog</h1>
                            <span class="subheading">CODER'S HOUSE BLOG</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container position-relative px-4 px-lg-5"">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7 search">
                        <form action="/post/post_search" method="GET">
                            <div class="custom-search-input">
                                <div class="input-group">
                                    <input type="text" class="form.control bg-light border-0 small" name="autor_search"  placeholder="Search">
                                    <div class="input-group-list">                                        
                                        <button type="submit" class="btn btn-primary"> Search
                                            <i class="fa fa-search" ></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            
                        </form>    
                    </div>
                </div>
            </div>
        </header>
        <!--Esto es lo que va a cambiar -->
        {% block app_coder_blog_content %}

        {% endblock%}

        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item">
                            <a href="{% url 'home:about-us' %}">About As</a></li>
                        <li class="list-inline-item">⋅</li>
                        <li class="list-inline-item"><a href="{% url 'home:pagina-error' %}">Contact</a></li>
                    </ul>
                </div>
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="{% url 'home:pagina-error' %}">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'home:pagina-error' %}">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="{% url 'home:pagina-error' %}">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Coder Blog 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js'%}"></script>
    </body>
</html>

home/templates/home/main.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}
    <h1> This blog was created by Amadeo Miotto</h1>

    <hr></hr>

    {% if user.is_authenticated %}
    <div class="text-center">
        <h2>Welcome {{ user.username }}!</h2>
        <h3><a style="color: rgb(3, 36, 184)" href="{% url 'user:avatar-load' %}">Change Avatar</a></h3>
        <img height="160px" src="{{url}}" alt="">
    </div>
    {% endif %}
    <hr>
    <hr></hr>
    <h1><strong>Publications</strong></h1>
    <hr></hr>
    <hr>
    {% if posts %}
    <ul>
        {% for post in posts %}
            <li>
                <h1><strong>{{post.title}}  </strong> </h1>
                <h2><strong>{{post.subtitle}}</strong></h2>
                    (
                        <a href="{% url 'post:post-detail' post.id %}">
                            <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
                        </a>
                    )
            </li>
            <hr></hr>
        {% endfor %}
    </ul>
    {% else %}
    <p>No Publications yet.</p>
    {% endif %}
    <hr></hr>
{% endblock %}

home/templates/home/pagina_error.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<div class="small text-center text-muted fst-italic"><h1><strong>Work in Progress...</strong></h1></div>

{% endblock %}