Entrega_Final_Arcenilla_Miotto/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('post/', include('post.urls')),
    path('comment/', include('comment.urls')),
    path('user/', include('user.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path
from comment import views

app_name='comment'
urlpatterns =[
    path('comentarios',views.comentarios, name='Comentarios'),
    path('comentario_formulario/<int:pk>', views.comentario_formulario , name='ComentarioFormulario'),
]

home/urls.py
from django.urls import path

from home import views

app_name='home'
urlpatterns = [
    path('', views.main, name='main'),
    path('pagina_error', views.pagina_error, name='pagina-error'),
    path('about_us', views.about_us, name='about-us'),
]

post/urls.py
from django.urls import path
from post import views

app_name='post'
urlpatterns =[
    path('post', views.PostListView.as_view(), name='post-list'),
    path('post/add/', views.PostCreateView.as_view(), name='post-add'),
    path('post/<int:pk>/detail', views.PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', views.PostDeleteView.as_view(), name='post-delete'),
    path('post_search', views.post_search, name='post-search'),
    path('imagen/<int:pk>/load', views.imagen_load, name='imagen-load'),
    
]

user/urls.py
from django.urls import path

from user import views


app_name='user'
urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path('user/<int:pk>/detail', views.AutorDetailView.as_view(), name='autor-detail'),
]

comment/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class Comentario(models.Model):
    descripcion=models.CharField(max_length=200)  
    autor=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,null=True)
    post=models.ForeignKey('post.Post',on_delete=models.CASCADE,null=True)
    fecha_publicacion=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'Comentario: Description: {self.descripcion} --- Author:Nombre:{self.autor} --- Date of Publication: {self.fecha_publicacion}'

post/models.py
from cgitb import enable
from datetime import datetime
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

# Create your models here.

class Post(models.Model):
    title=models.TextField(max_length=100)
    subtitle=models.TextField(max_length=80)
    texto= RichTextField()
    autor=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,null=True)  #-- preguntar
    fecha_publicacion=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'Titulo: {self.title} --- Autor: Nombre:{self.autor} --- Fecha de Publicación: {self.fecha_publicacion}'

    def get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular
        """
        return reverse('post:post-detail', args=[str(self.id)])

class PostImagen(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='imagenes', null=True, blank=True)

    def __str__(self):
        return f'url: {self.image.url}'

post/forms.py
from django import forms
from post.models import PostImagen

class ImagenForm(forms.ModelForm):
    class Meta:
        model = PostImagen
        fields = ('image', )

post/views.py
import os
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from post.forms import ImagenForm
from post.models import Post, PostImagen
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect

from user.models import User





# Create your views here.
class PostListView(ListView):
    model=Post
    template_name="post/post_list.html"

class PostDetailView(DetailView):
    model=Post
    template_name="post/post_detail.html"

class PostCreateView(LoginRequiredMixin,CreateView):
    model=Post
    success_url: reverse_lazy('post:post-list')
    fields=['title','subtitle','texto','autor']

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model=Post
    success_url='/'

class PostUpdateView(LoginRequiredMixin,UpdateView):
    model= Post
    success_url: reverse_lazy('post:post-list')
    fields=['title','subtitle','texto']

def post_search(request):
    context_dict = dict()
    if request.method == 'GET':
        if request.GET.get('autor_search') and request.GET.get('fecha_search'):
            search_param1 = request.GET.get('autor_search')
            search_param2 = request.GET.get('fecha_search')
            query = Q(autor__username__icontains=search_param1)
            query.add(Q(autor__first_name__icontains=search_param1), Q.OR)
            query.add(Q(autor__last_name__icontains=search_param1), Q.OR) 
            query.add(Q(autor__last_name__icontains=search_param1), Q.OR)
            query.add(Q(fecha_publicacion__contains=search_param2), Q.AND)
            posts = Post.objects.filter(query)
            context_dict = {
                'posts': posts
            }
        elif request.GET.get('autor_search') :
            search_param = request.GET.get('autor_search')           
            query = Q(autor__username__icontains=search_param)
            query.add(Q(autor__first_name__icontains=search_param), Q.OR)
            query.add(Q(autor__last_name__icontains=search_param), Q.OR) 
            posts = Post.objects.filter(query)
            context_dict = {
                'posts': posts
            }
        elif request.GET.get('fecha_search'):
            search_param = request.GET.get('fecha_search')
            posts = Post.objects.filter(fecha_publicacion__contains=search_param)
            context_dict = {
                'posts': posts
            }
    return render(
            request=request,
            context=context_dict,
            template_name="post/post_search.html",
        )

@login_required
def imagen_load(request,pk):
    if request.method == 'POST':
        form = ImagenForm(request.POST, request.FILES)
        if form.is_valid  and len(request.FILES) != 0:
            imagen = request.FILES['image']
            imagenes = PostImagen.objects.filter(post__id=pk)
            posts=Post.objects.get(id=pk)
            if not imagenes.exists():
                imagen = PostImagen(post=posts, image=imagen)
            else:
                imagen = imagenes[0]
                if len(imagen.image) > 0:
                    os.remove(imagen.image.path)
                imagen.image = imagen
            imagen.save()
            messages.success(request, "Imagen cargada exitosamente")
            return redirect('home:main')

    form= ImagenForm()
    return render(
        request=request,
        context={"form": form},
        template_name="post/post_imagen_form.html",
    )

post/templates/post/post_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h2>Delete Publication</h2>
<hr></hr>

<p>Confirm to delete publication: {{post.title }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn2 btn-warning" type="submit" value="Confirm to delete.">
    <a class="btn2 btn-primary" href="{% url 'post:post-list' %}" >Cancell</a>
</form>

{% endblock %}

post/templates/post/post_detail.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h1>Publication's details</h1>
<hr></hr>
<h1><strong>{{post.title}}  </strong> </h1>
<h2><strong>{{post.subtitle}}  </strong> </h2>
{{poasst.texto|safe}}  
{% for image in post.postimagen_set.all %}
    <img  src="{{image.image.url}}" alt="">
{% endfor %}

<p><h4>Published by  <a href="{% url 'user:autor-detail' post.autor.pk %}">{{ post.autor }}</a></p></h4>
<p><h4>Date of Publication: {{post.fecha_publicacion}}</h4></p>
<div style="margin-left:20px;margin-top:20px">
    <h4>Comments</h4>        
    {% for comment in post.comentario_set.all %}
    <hr>            
    <p><strong>Message:</strong> {{comment.descripcion}}</p>
    <p class="post-meta">
        Commented by 
        <a href="{% url 'user:autor-detail' comment.autor.pk %}">{{ comment.autor }}</a>
        {{comment.fecha_publicacion}}
    </p>
    <hr></hr>
    {% endfor %}
</div>
<a href="{% url 'post:post-list' %}">
    <i class="fa fa-reply" style="color: rgba(0, 0, 190, 0.623);"> </i>
    </a>
    
    
   <a href="{% url 'comment:ComentarioFormulario' post.id %}">
        <i class="fa fa-commenting" style="color: rgb(0, 0, 190, 0.623);"> </i>
    </a>

{% endblock %}

post/templates/post/post_form.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h2>Form to save/edit Publication</h2>
<hr></hr>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}    
    <input type="submit" class="btn btn-primary" value="Save Publication" />
</form>

{% endblock %}

post/templates/post/post_imagen_form.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h2>Form to upload image/avatar</h2>
<hr></hr>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Upload Image</button>
</form>

{% endblock %}

post/templates/post/post_list.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}
<h1>Publications</h1>
{% if user.is_authenticated %}  
    {% if user.perfil == "E" or user.perfil == "A" or user.is_superuser %}  
        <a class="btn btn-primary" href="{% url 'post:post-add' %}">Create a new Publication</a>
    {% endif %}
{% endif %}

<h2>Publication's list</h2>

<hr></hr>
{% if post_list %}
<ul>
    {% for post in post_list %}
    <li>

        <h1><strong>{{post.title}}  </strong> </h1>
        <h2><strong>{{post.subtitle}}  </strong> </h2>
        <hr></hr>
        <p><strong>Author:</strong> <a href="{% url 'user:autor-detail' post.autor.pk %}">{{ post.autor }}</a> {{post.fecha_publicacion}}</p> 
        
        (
        <a href="{% url 'post:post-detail' post.id %}">
            <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
        </a>
        {% if user.is_authenticated %}
            |
            <a href="{% url 'comment:ComentarioFormulario' post.id %}">
                <i class="fa fa-commenting" style="color: rgb(0, 0, 190);"> </i>
            </a>
            {% if user.username == post.autor.username or user.is_superuser %}
            |
            <a href="{% url 'post:post-update' post.id %}">
                <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
            </a>
            |
            <a href="{% url 'post:imagen-load' post.id %}">
                <i class="fa fa-image" style="color: rgb(0, 0, 190);"> </i>
            </a>
            |
            <a href="{% url 'post:post-delete' post.id %}">
                <i class="fa fa-trash" style="color: rgb(0, 0, 100);"> </i>
            </a>
            {% endif %}
        {% endif %}
        )
        <hr>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No Publications available.</p>
{% endif %}

{% endblock %}

post/templates/post/post_search.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h1>Search a Publication</h1>
<h2>Enter name, last name ,user name or date of  publication </h2>
<hr></hr>

<form action="/post/post_search" method="GET">
    <div>
        <input type="text" name="autor_search" id="autor_cod" placeholder="Search by Author">
    </div>
    <div>
        <input type="date" name="fecha_search" id="fecha_publicacion_cod" placeholder="Search by Date">
    </div>
    <div>
        <input type="submit" value="Search">
    </div>
</form>
<hr></hr>

{% if posts %}
    <ul>
        {% for post in posts %}
            <li>
                <h1><strong>{{post.title}}  </strong> </h1>
                <h2><strong>{{post.subtitle}}</strong></h2>
                    (
                        <a href="{% url 'post:post-detail' post.id %}">
                            <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
                        </a>
                    )
            </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No publications available.</p>
    {% endif %}

{% endblock %}