Entrega_Final_Arcenilla_Miotto/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('post/', include('post.urls')),
    path('comment/', include('comment.urls')),
    path('user/', include('user.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home import views

app_name='home'
urlpatterns = [
    path('', views.main, name='main'),
    path('pagina_error', views.pagina_error, name='pagina-error'),
    path('about_us', views.about_us, name='about-us'),
]

post/urls.py
from django.urls import path
from post import views

app_name='post'
urlpatterns =[
    path('post', views.PostListView.as_view(), name='post-list'),
    path('post/add/', views.PostCreateView.as_view(), name='post-add'),
    path('post/<int:pk>/detail', views.PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete', views.PostDeleteView.as_view(), name='post-delete'),
    path('post_search', views.post_search, name='post-search'),
    path('imagen/<int:pk>/load', views.imagen_load, name='imagen-load'),
    
]

user/urls.py
from django.urls import path

from user import views


app_name='user'
urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path('user/<int:pk>/detail', views.AutorDetailView.as_view(), name='autor-detail'),
]

user/models.py
from datetime import datetime
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


# Create your models here.
class Avatar(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatars', null=True, blank=True)

    def __str__(self):
        return f'url: {self.image.url}'

class User(AbstractUser):
    fecha_nacimiento=models.DateField(default='1950-05-04')
    fecha_y_hora_creacion=models.DateTimeField(auto_now_add=True)
    tipo_perfil  = (
        ('E', 'Editor'),
        ('L', 'Lector'),
        ('A', 'Administrador'),
        )
    perfil=models.CharField(
        max_length=1,
        choices=tipo_perfil,
        blank=True,
        default='L',
        help_text='Perfil del Usuario')
    
    def get_absolute_url(self):
        return reverse('autor-detail', args=[str(self.id)])

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from user.models import User
from django.forms import ModelForm
from user.models import Avatar

class UserRegisterForm(UserCreationForm):

    username = forms.CharField(label='Username', min_length=3)
    first_name = forms.CharField(label='Name', min_length=3)
    last_name = forms.CharField(label='Last name', min_length=3)
    email = forms.EmailField(label='e-mail')
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)
    fecha_nacimiento=forms.DateField(
        label='Date of publication',
        widget=forms.TextInput(attrs={'placeholder': 'yyyy-mm-dd'})
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2','fecha_nacimiento']
        help_texts = {k: "" for k in fields}


class UserEditForm(UserCreationForm):
    password = None

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'perfil']
        widgets = {
            'email': forms.TextInput(attrs={'readonly': 'readonly'}),
        }
        help_texts = {k: "" for k in fields}



class AvatarForm(ModelForm):
    class Meta:
        model = Avatar
        fields = ('image', )

user/views.py
from msilib.schema import ListView
import os
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from post.models import Post
from user.forms import UserRegisterForm, UserEditForm, AvatarForm
from user.models import Avatar, User
from django.contrib import messages
from django.forms import model_to_dict
from django.views.generic.detail import DetailView



# Create your views here.
def register(request):

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Usuario creado exitosamente!")
            return redirect("user:user-login")
        else: messages.error(request,"Datos Inválidos")
    form = UserRegisterForm()
    
    return render(
        request=request,
        context={"form":form},
        template_name="user/register.html",
    )


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home:main")

        return render(
            request=request,
            context={'form': form},
            template_name="user/login.html",
        )

    form = AuthenticationForm()
    return render(
        request=request,
        context={'form': form},
        template_name="user/login.html",
    )


def logout_request(request):
    logout(request)
    return redirect("user:user-login")

@login_required
def user_update(request):
    user = request.user
    if request.method == 'POST':
        form = UserEditForm(request.POST)
        if form.is_valid():
            informacion = form.cleaned_data
            user.first_name = informacion['first_name']
            user.last_name = informacion['last_name']
            user.email = informacion['email']
            user.password1 = informacion['password1']
            user.password2 = informacion['password2']
            user.perfil=informacion['profile']
            user.save()

            return redirect('home:main')

    form= UserEditForm(model_to_dict(user))
    return render(
        request=request,
        context={'form': form},
        template_name="user/user_form.html",
    )


@login_required
def avatar_load(request):
    if request.method == 'POST':
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid  and len(request.FILES) != 0:
            image = request.FILES['image']
            avatars = Avatar.objects.filter(user=request.user.id)
            if not avatars.exists():
                avatar = Avatar(user=request.user, image=image)
            else:
                avatar = avatars[0]
                if len(avatar.image) > 0:
                    os.remove(avatar.image.path)
                avatar.image = image
            avatar.save()
            messages.success(request, "Imagen cargada exitosamente")
            return redirect('home:main')
            

    form= AvatarForm()
    return render(
        request=request,
        context={"form": form},
        template_name="user/avatar_form.html",
    )
class AutorDetailView(DetailView):
    model=User
    template_name="user/autor_detail.html"

user/templates/user/autor_detail.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h2>Author's deatils</h2>
<hr></hr>
<p><h3>User: {{user.username}}</h3></p>
<p><h4>Name: {{user.first_name}}</h4></p>
<p><h4>Last name: {{user.last_name}}</h4></p>
<p><h4>Email: {{user.email}}</h4></p>
<p><a class="btn2 btn-primary" href="{% url 'post:post-list' %}">Go back</a></p>
{% endblock %}

user/templates/user/avatar_form.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h2>Form to upload Avatar's image</h2>
<hr></hr>
<h3>User: {{user.username}}</h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Upload Image</button>
</form>

{% endblock %}

user/templates/user/login.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h2>Login</h2>
<hr></hr>

{% if form.errors %}
<p style="color: red">Wrong username and password, please try again.</p>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <div>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </div>
    <div>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </div>
    <a class="btn2 btn-dark" href="{% url 'user:user-register' %}" >Register</a>
    <button type="submit">Log in</button>
</form>

{% endblock %}

user/templates/user/register.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h2>Register</h2>
<h3>Please fill out the form, password must be strong and valid </h3>
<li>Your password can’t be too similar to your other personal information.</li>
<li>Your password must contain at least 8 characters.</li>
<li>Your password can’t be a commonly used password.</li>
<li>Your password can’t be entirely numeric.  </li>  
<hr></hr>
{% if messages %}
    {% for message in messages %}
        <li style="color: blue"> {{ message }} </li>
    {% endfor %}
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register User</button>
</form>

{% endblock %}

user/templates/user/user_form.html
{% extends "home/index.html" %}
{% load static %}
{% block app_coder_blog_content %}

<h2>Form to edit users</h2>
<hr></hr>
<h3>User: {{user.username}}</h3>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Save" />
</form>

{% endblock %}